# theme = "adwaita-dark"
theme = "gruvbox"
[editor]
auto-save = true
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"
scrolloff = 10
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
character = "│"
render = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = false

[editor.statusline]
center = ["workspace-diagnostics", "version-control"]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "total-line-numbers", "position-percentage", "file-encoding"]

[editor.inline-diagnostics] 
cursor-line = "hint" 
other-lines = "disable"

[keys.normal]
X = ["goto_first_nonwhitespace", "select_mode", "goto_line_end", "normal_mode"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
"+" = "@<space>=\"=q"
"e" = [":write-all", ":sh wezterm cli split-pane --bottom yazi"]

[keys.normal.m]
l = "@f(;mim<A-;>m"
h = "@h<S-F>(;mi(<A-;>m"
j = "@f{mi{<A-;>m"
k = "@h<S-F>{;mi{<A-;>m"
"." = "@f<lt>mi<lt><A-;>m"
"," = "@h<S-F><lt>mi<lt>"
c = ["change_selection"]
D = ["delete_selection"]
y = ["yank"]
g = "@g"

[keys.insert]
"C-q" = ["record_macro"]


